({
    fetchData: function (component) {
        var results = [
  {
    "Referral_ID": "DIG140902",
    "Referral_Category": "DBT",
    "Record_Type": "P",
    "Referral_Date": "Sat Sep 26 1987 18:19:54 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Sat Feb 16 2019 19:05:47 GMT-0600 (Central Standard Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "OPTICOM",
    "Merchant_City": "Boling",
    "Corp_Set_Name": "EMTRAK",
    "Issuer": "ZAGGLES",
    "Issuer_Type": "KINDALOO",
    "AcquirerName": "AQUASSEUR",
    "UserName": "Carissa",
    "DueDate": "Sat Apr 13 2019 09:14:35 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "Web",
    "PriorityIssuer": false,
    "Priority_Merchant": true,
    "Priority_Level": "P2",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG873407",
    "Referral_Category": "Digital",
    "Record_Type": "P",
    "Referral_Date": "Sat Feb 22 1997 18:24:48 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sun Jun 30 2019 03:31:40 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "DATACATOR",
    "Merchant_City": "Munjor",
    "Corp_Set_Name": "EXOPLODE",
    "Issuer": "OLUCORE",
    "Issuer_Type": "ULTRASURE",
    "AcquirerName": "BIFLEX",
    "UserName": "Maureen",
    "DueDate": "Wed Mar 27 2019 06:51:33 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG152400",
    "Referral_Category": "DBT",
    "Record_Type": "P",
    "Referral_Date": "Mon Nov 18 1996 00:05:05 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sun Feb 17 2019 00:17:56 GMT-0600 (Central Standard Time)",
    "Assigned_To": "International",
    "Referral_Status": "Open",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "COLUMELLA",
    "Merchant_City": "Marbury",
    "Corp_Set_Name": "EWEVILLE",
    "Issuer": "ZORROMOP",
    "Issuer_Type": "TINGLES",
    "AcquirerName": "GEOFORMA",
    "UserName": "Mcneil",
    "DueDate": "Thu Jan 10 2019 21:20:34 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG117259",
    "Referral_Category": "EMV",
    "Record_Type": "P",
    "Referral_Date": "Sun Jun 08 2014 22:46:14 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Thu Jul 04 2019 02:31:46 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "International",
    "Referral_Status": "Open",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "HINWAY",
    "Merchant_City": "Riviera",
    "Corp_Set_Name": "OPTYK",
    "Issuer": "MOMENTIA",
    "Issuer_Type": "ZIPAK",
    "AcquirerName": "VINCH",
    "UserName": "Fowler",
    "DueDate": "Tue Sep 03 2019 16:49:51 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "Web",
    "PriorityIssuer": false,
    "Priority_Merchant": false,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG395798",
    "Referral_Category": "EMV",
    "Record_Type": "P",
    "Referral_Date": "Tue Apr 04 2017 22:26:51 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Wed Mar 13 2019 20:22:51 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "DENTREX",
    "Merchant_City": "Holtville",
    "Corp_Set_Name": "UNQ",
    "Issuer": "EXODOC",
    "Issuer_Type": "EZENTIA",
    "AcquirerName": "OVERFORK",
    "UserName": "Bonner",
    "DueDate": "Thu Oct 03 2019 19:26:07 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": false,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG211819",
    "Referral_Category": "DBT",
    "Record_Type": "P",
    "Referral_Date": "Mon Dec 04 1978 07:19:00 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sun Mar 03 2019 14:55:17 GMT-0600 (Central Standard Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "SCHOOLIO",
    "Merchant_City": "Greenbackville",
    "Corp_Set_Name": "ZENTILITY",
    "Issuer": "FOSSIEL",
    "Issuer_Type": "COLAIRE",
    "AcquirerName": "SLOFAST",
    "UserName": "Maryellen",
    "DueDate": "Mon Nov 04 2019 04:55:58 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "Web",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG375726",
    "Referral_Category": "Digital",
    "Record_Type": "P",
    "Referral_Date": "Sat Dec 13 1975 13:45:53 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Tue May 07 2019 18:07:13 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "CCoE",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "KIOSK",
    "Merchant_City": "Ripley",
    "Corp_Set_Name": "ZOINAGE",
    "Issuer": "EARWAX",
    "Issuer_Type": "SIGNIDYNE",
    "AcquirerName": "ZEPITOPE",
    "UserName": "Bianca",
    "DueDate": "Tue Dec 10 2019 14:17:35 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": false,
    "Priority_Merchant": true,
    "Priority_Level": "P2",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG596159",
    "Referral_Category": "DBT",
    "Record_Type": "P",
    "Referral_Date": "Wed May 30 1979 09:14:30 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Wed Dec 11 2019 12:16:02 GMT-0600 (Central Standard Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Closed",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "VETRON",
    "Merchant_City": "Lookingglass",
    "Corp_Set_Name": "EARTHMARK",
    "Issuer": "BLUPLANET",
    "Issuer_Type": "FARMAGE",
    "AcquirerName": "TRIBALOG",
    "UserName": "Lindsay",
    "DueDate": "Sun Dec 16 2018 23:58:00 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "XX",
    "Source": "Web",
    "PriorityIssuer": false,
    "Priority_Merchant": false,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG263369",
    "Referral_Category": "Digital",
    "Record_Type": "P",
    "Referral_Date": "Sat Feb 16 1980 16:10:12 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sat Aug 03 2019 21:56:47 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "International",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "EQUICOM",
    "Merchant_City": "Waikele",
    "Corp_Set_Name": "CEPRENE",
    "Issuer": "NEPTIDE",
    "Issuer_Type": "ZILENCIO",
    "AcquirerName": "SEQUITUR",
    "UserName": "Aida",
    "DueDate": "Sat Dec 21 2019 22:30:31 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG143431",
    "Referral_Category": "EMV",
    "Record_Type": "P",
    "Referral_Date": "Sat Apr 16 2011 05:28:14 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Sun May 19 2019 03:21:28 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "International",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "ECLIPTO",
    "Merchant_City": "Mapletown",
    "Corp_Set_Name": "SOLGAN",
    "Issuer": "VERAQ",
    "Issuer_Type": "GAZAK",
    "AcquirerName": "PLASMOX",
    "UserName": "Katrina",
    "DueDate": "Sun Jun 09 2019 17:15:03 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": false,
    "Priority_Merchant": true,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG194789",
    "Referral_Category": "DBT",
    "Record_Type": "C",
    "Referral_Date": "Fri Sep 20 1974 16:17:44 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Wed Mar 06 2019 04:47:38 GMT-0600 (Central Standard Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "BRISTO",
    "Merchant_City": "Babb",
    "Corp_Set_Name": "REMOLD",
    "Issuer": "ZOLAVO",
    "Issuer_Type": "TELEPARK",
    "AcquirerName": "EXOTERIC",
    "UserName": "Rachelle",
    "DueDate": "Thu Aug 22 2019 18:47:38 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": false,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG870093",
    "Referral_Category": "DBT",
    "Record_Type": "P",
    "Referral_Date": "Sat Jun 01 1996 14:56:44 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Wed Jun 12 2019 18:34:18 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Closed",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "BUZZNESS",
    "Merchant_City": "Oneida",
    "Corp_Set_Name": "OVATION",
    "Issuer": "FARMEX",
    "Issuer_Type": "ASSISTIX",
    "AcquirerName": "UNIA",
    "UserName": "Silva",
    "DueDate": "Thu Feb 28 2019 12:29:16 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "Acceptance",
    "Source": "Web",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG354491",
    "Referral_Category": "Digital",
    "Record_Type": "C",
    "Referral_Date": "Tue May 03 1983 00:52:28 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Sat Mar 23 2019 05:53:41 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "International",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "TASMANIA",
    "Merchant_City": "Florence",
    "Corp_Set_Name": "GYNKO",
    "Issuer": "OZEAN",
    "Issuer_Type": "QUINEX",
    "AcquirerName": "ROBOID",
    "UserName": "Sheppard",
    "DueDate": "Wed Dec 19 2018 20:13:19 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": false,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG695667",
    "Referral_Category": "Digital",
    "Record_Type": "C",
    "Referral_Date": "Tue Jul 31 1990 08:40:21 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Sat Aug 24 2019 02:57:31 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Closed",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "ACCEL",
    "Merchant_City": "Lorraine",
    "Corp_Set_Name": "SINGAVERA",
    "Issuer": "AMTAS",
    "Issuer_Type": "ZENTIX",
    "AcquirerName": "LIQUIDOC",
    "UserName": "Copeland",
    "DueDate": "Sat Jun 01 2019 12:16:57 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG201369",
    "Referral_Category": "Digital",
    "Record_Type": "C",
    "Referral_Date": "Wed Jan 07 1970 17:00:42 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Thu Jan 03 2019 11:38:16 GMT-0600 (Central Standard Time)",
    "Assigned_To": "International",
    "Referral_Status": "Closed",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "PARLEYNET",
    "Merchant_City": "Glidden",
    "Corp_Set_Name": "QUOTEZART",
    "Issuer": "SONGBIRD",
    "Issuer_Type": "PREMIANT",
    "AcquirerName": "SYBIXTEX",
    "UserName": "Wells",
    "DueDate": "Wed Feb 06 2019 12:04:49 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "Web",
    "PriorityIssuer": true,
    "Priority_Merchant": true,
    "Priority_Level": "P1",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG308045",
    "Referral_Category": "DBT",
    "Record_Type": "C",
    "Referral_Date": "Thu Feb 10 1994 20:42:54 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sat May 04 2019 07:45:28 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "POLARAX",
    "Merchant_City": "Bynum",
    "Corp_Set_Name": "XYMONK",
    "Issuer": "OBLIQ",
    "Issuer_Type": "BOSTONIC",
    "AcquirerName": "GORGANIC",
    "UserName": "Madelyn",
    "DueDate": "Wed Jul 31 2019 21:21:13 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "Web",
    "PriorityIssuer": true,
    "Priority_Merchant": false,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": true,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG578586",
    "Referral_Category": "EMV",
    "Record_Type": "C",
    "Referral_Date": "Wed Jun 07 2006 04:27:45 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Sat Feb 16 2019 20:48:58 GMT-0600 (Central Standard Time)",
    "Assigned_To": "International",
    "Referral_Status": "Open",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "EARTHWAX",
    "Merchant_City": "Crumpler",
    "Corp_Set_Name": "PLASMOS",
    "Issuer": "BIOHAB",
    "Issuer_Type": "ZOUNDS",
    "AcquirerName": "TERRAGO",
    "UserName": "Martina",
    "DueDate": "Thu Mar 28 2019 10:29:53 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "Acceptance",
    "Source": "XX",
    "PriorityIssuer": false,
    "Priority_Merchant": false,
    "Priority_Level": "P2",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG286631",
    "Referral_Category": "Digital",
    "Record_Type": "C",
    "Referral_Date": "Mon Aug 02 1999 22:21:55 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Tue Jan 22 2019 13:15:29 GMT-0600 (Central Standard Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "NEW",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "EWAVES",
    "Merchant_City": "Salix",
    "Corp_Set_Name": "CORPULSE",
    "Issuer": "BUZZWORKS",
    "Issuer_Type": "GAPTEC",
    "AcquirerName": "NORALEX",
    "UserName": "Weber",
    "DueDate": "Wed Oct 23 2019 17:54:29 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "Acceptance",
    "Source": "Web",
    "PriorityIssuer": true,
    "Priority_Merchant": false,
    "Priority_Level": "P2",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": false,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG866632",
    "Referral_Category": "DBT",
    "Record_Type": "C",
    "Referral_Date": "Wed Feb 20 2013 19:23:07 GMT-0600 (Central Standard Time)",
    "Next_Followup_Date": "Sun Dec 30 2018 06:04:04 GMT-0600 (Central Standard Time)",
    "Assigned_To": "CCoE",
    "Referral_Status": "Closed",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "GLEAMINK",
    "Merchant_City": "Weeksville",
    "Corp_Set_Name": "BALOOBA",
    "Issuer": "SEALOUD",
    "Issuer_Type": "CORIANDER",
    "AcquirerName": "ISOLOGIX",
    "UserName": "Rivera",
    "DueDate": "Wed Jan 09 2019 16:50:57 GMT-0600 (Central Standard Time)",
    "Purchase_Type": "XX",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": false,
    "Priority_Merchant": false,
    "Priority_Level": "P3",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": false,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": false,
    "Chipcard_Attempted": true,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  },
  {
    "Referral_ID": "DIG357485",
    "Referral_Category": "Digital",
    "Record_Type": "C",
    "Referral_Date": "Mon Apr 21 2008 18:54:14 GMT-0500 (Central Daylight Time)",
    "Next_Followup_Date": "Fri Jul 19 2019 10:29:12 GMT-0500 (Central Daylight Time)",
    "Assigned_To": "Customer Experience",
    "Referral_Status": "Open",
    "StatusType": "OLD",
    "Disposition": "NEW REQUEST",
    "Merchant_Name": "ZILLACTIC",
    "Merchant_City": "Ballico",
    "Corp_Set_Name": "PRIMORDIA",
    "Issuer": "TURNLING",
    "Issuer_Type": "ANDRYX",
    "AcquirerName": "ISOTRACK",
    "UserName": "Alta",
    "DueDate": "Thu Jun 13 2019 19:07:13 GMT-0500 (Central Daylight Time)",
    "Purchase_Type": "IVR",
    "Referral_Type": "XX",
    "Source": "XX",
    "PriorityIssuer": false,
    "Priority_Merchant": true,
    "Priority_Level": "P2",
    "Referral_Origin": "Cardholder Reported Failure",
    "Campaign": "Debit Camp",
    "Discover_Accepted": true,
    "Checkout": "Use a Kiosk/Self Checkout",
    "Is_this_a_Debit_or_Credit_Card": false,
    "PIN_Pad": true,
    "Payment_Options_Prompted": "Credit",
    "PINCashback_Capability": "Dont Know",
    "Cashback_Successful": true,
    "Chipcard_Attempted": false,
    "Chipcard_Used_in_Following_Manner": "Dont Know"
  }
];
   console.log("Dummy Data is",results);
	component.set('v.data', results);
       
        
    }
})